#!/usr/bin/env python3
import sys
import matching
import InitAnswers

if len(sys.argv) < 3:
    raise Exception('Too few arguments')

article_filename = sys.argv[1]
article = open(article_filename, 'r', encoding="utf-8")

questions_filename = sys.argv[2]
questions = open(questions_filename, 'r', encoding="utf-8")
questions1 = open(questions_filename, 'r', encoding="utf-8")

# dummy answers
doc = article.read()
matches = [matching.matching_sentence(doc, q) for q in questions]

InitAnswers.main(questions1.readlines(), matches)
