#!/usr/bin/env python3
import sys

if len(sys.argv) < 3:
    raise Exception('Too few arguments')

article_filename = sys.argv[1]
article = open(article_filename, 'r')

questions_filename = sys.argv[2]
questions = open(questions_filename, 'r')

# dummy answers
answers = ["I am me." for q in questions]

for a in answers:
    print(a)
